services:
  - type: web
    name: onaspark
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
